### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ajaycode10x** [Alkaison/Number-System-Converter#2]

**Comment by Alkaison** [comment]
Hello @ajaycode10x, How are you? 

Why this issue?

**Comment by ajaycode10x** [comment]
> Hello @ajaycode10x, How are you? 
> 
> Why this issue?

I'm fine.

I just find a simple c program code for my
Internal exam.

**Comment by Alkaison** [comment]
> 
> I'm fine.
> 
> I just find a simple c program code for my Internal exam.

Oh great, I hope you find something useful on GitHub.

You can check my other projects too in C language here: https://github.com/Alkaison?tab=repositories&q=&type=&language=c&sort=
